# Generated by Django 4.2.3 on 2023-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorize',
            name='name',
            field=models.CharField(default='Auth_first_time_usr', max_length=50),
            preserve_default=False,
        ),
    ]
