# Generated by Django 4.2.3 on 2023-08-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_authorize_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorize',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Admin'), (-1, 'Test'), (1, 'User'), (2, 'Librarian'), (3, 'Guest')]),
        ),
        migrations.CreateModel(
            name='Assigned_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=90)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.authorize')),
            ],
        ),
    ]
