# Generated by Django 4.2.3 on 2023-09-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorize',
            name='password',
        ),
    ]
