# Generated by Django 4.2.3 on 2023-08-15 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_libraryentity_access_rights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assigned_materials',
            new_name='Assigned_material',
        ),
    ]
