# Generated by Django 4.2.3 on 2023-08-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_authorize_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorize',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assigned_material'),
        ),
    ]
