# Generated by Django 4.2.3 on 2023-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_authorize_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorize',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='authorize',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='authorize',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
