# Generated by Django 4.2.3 on 2023-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_authorize_options_authorize_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_material',
            name='library_entity_id',
        ),
        migrations.AlterField(
            model_name='authorize',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authorize',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
