# Generated by Django 4.2.3 on 2023-08-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_assigned_material_library_entity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_material',
            name='library_entity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.libraryentity'),
        ),
    ]
