# Generated by Django 4.2.3 on 2023-08-20 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_assigned_material_library_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorize',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
