# Generated by Django 4.2.3 on 2023-08-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_authorize_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigned_material',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='authorize',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book'),
        ),
    ]
