# Generated by Django 4.2.3 on 2023-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_assigned_material_options_authorize_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorize',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
