# Generated by Django 4.2.3 on 2023-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_filehandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandler',
            name='title',
            field=models.CharField(default='new', max_length=200),
            preserve_default=False,
        ),
    ]
